Bridge mode
zyclonite/zerotier-docker pull request #6
Opened 2022-01-19 08:04 UTC by red-avtovo

Added K8S deployment file for the reference
Added bridge mode

2022-01-24 15:31 UTC, zyclonite commented
thank you for your contribution

i will have a more detailed look into the use-case
just some thoughts on your solution

* the main idea for this project was to keep the image as small as possible
currently it has around 10MB but gets 66MB for only this bridge feature
* it is also an anti-pattern to run more than one process in the container (iptables, supervisord...)
* i would recommend logging everything to std-out as growing logfiles in a container could lead to issues

2022-01-24 15:42 UTC, red-avtovo commented
Hi!
Thank you for your comment. I also agree that multiple processes are not a good idea, but I didn't come up with something better than that because of some reasons:
- It will be so dirty to adjust an entry point and add an explicit call of `bridge.sh` in front of it
- `bridge.sh` is being executed in the background because it waits for the zerotier-one connections establishment and `zt` interface creation. It is impossible to predict its name and create iptables rules upfront
- supervisord was a cheap solution to keep the entrypoint same-ish and get additional control over background processes. In a good container-style way I should have run supervisord in non-daemon mode and move zerotier-one under its tasks

2022-01-24 15:43 UTC, red-avtovo commented
Totally agree with the minimal container size approach. Wasn't really see the way how to bring the feature in without affecting the fingerprint

2022-01-24 16:28 UTC, zyclonite commented
options i see without really validating them yet

1. have a side-car container handling the iptables
2. have a dedicated container built with a suffixed tag `-bridge`

2022-01-26 20:56 UTC, red-avtovo commented
The first approach doesn't seem like an easy setup to me, so I tend to agree with the second one. 
How would you like to proceed? Should you publish both of them or I will publish the bridged one in my fork?

2022-01-27 17:17 UTC, zyclonite commented
you can move you bridge addition to a separate docker file (e.g. `Dockerfile.bridge`) and start with `from zyclonite/zerotier`

then i can merge your PR and add a build step to push the bridge tag as well with every release

2022-01-27 20:47 UTC, zyclonite requested changes
some changes i would recommend

2022-01-27 20:47 UTC, zyclonite commented on Dockerfile.bridge
> +ARG ZT_VERSION=1.8.4
can be removed

2022-01-27 20:47 UTC, zyclonite commented on Dockerfile.bridge
> +    BRIDGE=false
as this will be anyway a different image tag, the environment variable can be removed as well

2022-01-27 20:47 UTC, zyclonite commented on Dockerfile.bridge
> +COPY scripts /opt
to create only one layer this could be `COPY conf scripts /opt`

2022-01-27 20:47 UTC, zyclonite commented on README.md
> +To enable it, remove the host network parameter and add `Bridge=true` to environment variables.
without env var

2022-01-27 20:47 UTC, zyclonite commented on README.md
> +    docker run --name zerotier-one --device=/dev/net/tun -e BRIDGE=true \
without env var

2022-01-27 20:47 UTC, zyclonite commented on README.md
> +      -v /var/lib/zerotier-one:/var/lib/zerotier-one zyclonite/zerotier-bridge
i would not create a new image name but only a tag `zyclonite/zerotier:bridge`

2022-01-27 20:47 UTC, zyclonite commented on k8s/deployment.yaml
> +            value: "true"
not needed

2022-01-27 20:47 UTC, zyclonite commented on k8s/deployment.yaml
> +        image: zyclonite/zerotier-bridge:latest
only tagged version `image: zyclonite/zerotier:bridge`

2022-01-27 20:47 UTC, zyclonite commented on scripts/bridge.sh
> +fi
can be removed

2022-01-29 10:35 UTC, zyclonite approved these changes
lgtm

2022-01-29 10:42 UTC, merged

2022-01-29 21:50 UTC, zyclonite commented
@red-avtovo can you test the final image?

2022-01-30 09:00 UTC, red-avtovo commented
Thank you very much for setting up a new CI pipeline and building the image so quickly!
I've checked that on `amd64` and `arm64` and site-2-site connection works perfectly fine

I found one tiny issue though. My bridge script doesn't work well with DualStack setup, where you have 2 `zt` interfaces. That breaks the logic of the script, but it still works because:
- Masquerade is already applied
- The default iptables policy is ALLOW, so additional rules are redundant.

![image](https://user-images.githubusercontent.com/10682826/151693241-0e0c6650-63aa-49e4-87fa-a65854f45d19.png)

I think, that we can leave it as it is and update the script logic any time later. Wdyt?

2022-01-30 10:10 UTC, zyclonite commented
as far as i remember you can use `zt+` for iptables, so i would match all interfaces starting with zt

2022-01-30 10:41 UTC, red-avtovo commented
From [iptables doc](https://linux.die.net/man/8/iptables)
```
-i, --in-interface [!] name
Name of an interface via which a packet was received (only for packets entering the INPUT, FORWARD and PREROUTING chains). When the "!" argument is used before the interface name, the sense is inverted. If the interface name ends in a "+", then any interface which begins with this name will match. If this option is omitted, any interface name will match.
```

That is amazing 🤩 
Let me update the image

2022-01-30 11:31 UTC, red-avtovo commented
Improved with #7